<?php include('includes/header2.php'); ?>
	<div class="container content-container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="title">Terms and Conditions</h2>
				<p>Essex Funding, Inc. Web site is offered to you, the user ("User"), conditioned on acceptance of the terms, conditions, and notices contained herein and without modification. Your access and use of this site constitutes acceptance by you of all of these terms and conditions.</p>
				<p><strong>Web Site Use.</strong> The User agrees to use this Web site only as permitted by applicable local, state, and federal laws. Additionally, only the User agrees not to: 1) knowingly and without authorization, alter, damage, or destroy Essex Funding, Inc. or another user's computer system, network, software, Web site, program, documentation or the data contained therein; 2) use this Web site to conduct or attempt to conduct any business or activity or solicit the performance of any activity that is prohibited by law. Any action by the User that results in the blocking of access to this Web site by other users or Essex Funding, Inc. will be deemed an unauthorized use.</p>
				<p><strong>Monitoring of Use.</strong> By using this system, the User consents to administrative monitoring at all times. The User is hereby advised that system administrators may provide evidence of apparent criminal activity identified during such monitoring to appropriate law enforcement officials. If the User does not consent to any monitoring, the User should exit this system now.</p>
				<p><strong>Disclaimer.</strong> Every effort has been made by Essex Funding, Inc. to offer the most current, correct, and clearly expressed information possible. Nevertheless, it is possible that errors in information posted may occur. In particular, but without limitation to any portion of this Agreement, Essex Funding, Inc. disclaims any responsibility for inadvertent errors and the accuracy of any news, financial information, data, or other information that may be contained on Essex Funding, Inc. Web pages., The news, financial information, data and information included on Essex Funding, Inc. servers has been compiled by Essex Funding, Inc. personnel from a variety of sources and is subject to change without notice to the User. Essex Funding, Inc. makes no warranty or representation of any kind regarding the quality, content, completeness, suitability, accuracy, adequacy, sequence, or timeliness of the content found on this Web site.</p>
				<p><strong>Links to Third Parties' Web Sites.</strong> Essex Funding, Inc. Web pages may currently or in the future include links to Web sites that are controlled or operated by third parties. Sites linked to the Essex Funding, Inc. Web site are not necessarily under Essex Funding, Inc. control, and Essex Funding, Inc. assumes no responsibility or liability for any information, communications or materials at such sites, or at any Web site linked to a linked site. Essex Funding, Inc. does not intend that any third-party links be considered as referrals to or endorsements of the linked entities or any products and/or services marketed by them and such links are provided for convenience only. Each third party Web site has its own policies about what information is appropriate for public access. The user assumes sole responsibility for use of any third-party linked Web sites.</p>
				<p><strong>Intellectual Property.</strong> The User acknowledges that Essex Funding, Inc. Web site contains intellectual property that is protected by state and/or federal trademark, trade secret and/or copyright laws. The User agrees not to use, reproduce, distribute copies of, or create derivative works from any Essex Funding Inc.</p>
				<p><strong>Assumption of Risk.</strong> By using Essex Funding, Inc. Web pages for any purpose, the User assumes all risk associated with the use of this site and its individual pages. This risk includes, but is not limited to, any risk to the User's computer, software or data caused by any virus, software, or other file that might be transmitted or activated via Essex Funding, Inc. Web page or the User's access to it. Essex Funding, Inc. shall in no circumstance be liable for any direct, indirect, special, incidental, consequential, or punitive damages, including, but not limited to, lost profits or lost revenues, arising out of or in any way connected with the use or misuse of this Web site, or from any information, lack of information, documents, software, services, or other material obtained from or through any Essex Funding, Inc. Web pages. The User assumes any and all risk arising out of the use of this Web site, whether based in contract, tort, strict liability, or otherwise, even in the event that Essex Funding, Inc. and/or any of its employees, affiliates, or agents have been advised of the possibility of damages of any sort. Essex Funding, Inc. shall not be liable for any loss or injury caused in whole or in part by its actions, or omissions, or contingencies beyond its control, including, without limitation, the procuring, compiling, displaying, or delivering of information, or arising out of any errors, omissions, or inaccuracies in the information regardless of how caused, or arising out of any user's decision, or action taken, or not taken in reliance upon the information or lack of information furnished.</p>
				<p><strong>Forbidden Uses.</strong> UNDER NO CIRCUMSTANCE SHALL THE USER ACCESS OR ATTEMPT TO ACCESS CNH'S COMPUTER SYSTEM, COMPUTER NETWORK, OR ANY PART THEREOF FOR THE PURPOSE OF EXECUTING ANY OPERATION TO Essex Funding, Inc. reserves the right to terminate at its own discretion the User's use of this Web site or forbid the User from accessing this Web site in the future in the event of any abuse of the Web site or any unauthorized or forbidden use by the User.</p>
				<p><strong>Use of Interactive Media.</strong> To the extent that the Essex Funding, Inc. Web site contains or may contain electronic mail link Essex Funding, Inc. and/or other users, the User agrees to use such forums in their intended manner. Under no circumstances shall the User violate any law by using such forums for improper purposes including, but not limited to, defaming or harassing others, violating intellectual property rights of Essex Funding, Inc. or a third party, posting or sending obscene or offensive material, or introducing viruses, corrupted files or other programs that could damage or alter this Web site or the computers of Essex Funding, Inc. or of a third party. Essex Funding, Inc. reserves the right to remove any contents of this Web site for any reason whatsoever. The User acknowledges that any material posted by parties other than Essex Funding, Inc. or its affiliates is not endorsed by Essex Funding, Inc. or its affiliates, and such communications shall not be considered reviewed or approved by Essex Funding, Inc.</p>
				<p><strong>Indemnification.</strong> The User agrees to indemnify Essex Funding, Inc. its directors, officers, agents and employees, against any and all liability, expenses, attorney fees, and damages arising out of or relating to the use of this Web site in any way, including, without limitations, any claims alleging facts that, if true, would constitute a breach by the User of these terms and conditions.</p>
				<p><strong>No Contractual Relationship.</strong> The User acknowledges that, by the use of this Web site, no relationship of any kind, including but not limited to partnerships, joint ventures, employment or a contractual or agency relationship, exists between the User and Essex Funding, Inc. or any of its or its affiliates’ directors, officers, agents or employees.</p>
				<p><strong>Jurisdiction.</strong> These Terms and Conditions are and shall be governed by the laws of the State of Florida in the United States of America. The User consents to the exclusive jurisdiction and venue of courts located in Wisconsin, U.S.A., in all disputes arising out of or relating to the use of this Web site. Use of this Web site is not authorized in any jurisdiction that does not give effect to all provision of these terms and conditions. The User irrevocably waives any objection that it may have at any time to the venue of any suit, action or proceeding out of or relating to these Terms and Conditions brought in any such court and irrevocably waives any claim that such suit, action or proceeding is brought in an inconvenient forum and further irrevocably waives the right to object, with respect to any such claim, suit, action or proceeding brought in any such court, that such court does not have jurisdiction over the User.</p>
				<p><strong>Applicable Laws.</strong> Essex Funding, Inc. performance under these Terms and Conditions is subject to existing laws and legal process and nothing contained herein is in derogation of Essex Funding, Inc. right to comply with law enforcement requests or requirements relating to any party's use of this Web site or information provided to or collected by Essex Funding, Inc. regarding such use.</p>
				<p><strong>Survival.</strong> If any part of these Terms and Conditions is determined to be invalid or unenforceable pursuant to applicable law, the invalid or unenforceable provision will be deemed superseded by a valid and enforceable provision that closely resembles the intent of the original provision and the remainder of the Agreement shall continue in effect.</p>
				<p><strong>Entire Agreement.</strong> These Terms and Conditions constitutes the entire agreement between the User and Essex Funding Inc., regarding this Web site. These Terms and Conditions supersede all prior or contemporaneous communications made in any medium of expression between the User and Essex Funding, Inc. regarding this Web site and the subject matter of these Terms and Conditions.</p>
			</div>
		</div>
	</div>
	
<?php include('includes/footer.php'); ?>